### ISSUE TITLE
Item categories have not been initialized (BREAKING CHANGE - 7/29)

### ISSUE THREAD

**Issue by aiolos01** [gerwaric/acquisition#47]
It worked the last time I run it. Now it just says that message in the log window and displays nothing.

**Comment by gerwaric** [comment]
The categories are initialized by downloading and parsing files from RePoE. The error you're getting could happen if the network is down or maybe if GitHub did not respond in time.  If that's the case, this error might not happen if you try again later.

Specifically, these are the files acquisition tries to download:
- https://raw.githubusercontent.com/lvlvllvlvllvlvl/RePoE/master/RePoE/data/item_classes.min.json
- https://raw.githubusercontent.com/lvlvllvlvllvlvl/RePoE/master/RePoE/data//base_items.min.json

I'm especially interested if those links work when you copy them into the browser, but you're still seeing this error. That could mean there is some kind of race condition, where acquisition needs to wait for those downloads before opening the main window.

(Aside: I was once trying to test acquisition on in-flight wifi, and the network lag was so terrible I disovered some other issues like this)

**Comment by aiolos01** [comment]
If I get this error again I'll check and let you know. For the time being I installed the new version and it works. Not sure if the version change helped.
Thanks for adding tab delete. Such a useful feature.

**Comment by gerwaric** [comment]
If it happens again, I've been thinking about bundling those files into acquisition so we aren't relying on downloading something from GitHub. That would solve the problem, too.

**Comment by aiolos01** [comment]
I suppose this would be the best option since it doesn't rely on the existence of a github repository that belongs to someone else.

**Comment by duarm** [comment]
lvlvllvlvllvlvl broke acquisition with this change, there are no more .min.json files, resulting in an error

https://github.com/lvlvllvlvllvlvl/RePoE/commit/ad7952e6c2c05ec8a626fec2886e90ca01dffcdd

**Comment by gerwaric** [comment]
Thank you for the heads up. I might be able to get a fix out today, if it's as simple as swapping to the un-minified versions.

**Comment by gerwaric** [comment]
Let me know if this works for you now:

https://github.com/gerwaric/acquisition/releases/tag/v0.11.1

**Comment by duarm** [comment]
I'm actually on linux, instructions on how to build are unclear, I've been using the provided last release app image

**Comment by duarm** [comment]
I'm on archlinux, linux 6.10.2

**Comment by gerwaric** [comment]
I've uploaded an AppImage for Linux. Please let me know if it works.

The linux release are built on Cinammon Mint 20 virtual machine, and one tricky thing I've encountered is that acqusition needs SSL 3.x, but the app image creator won't include those libraries, so they still need to be installed locally on your system... I think.

**Comment by duarm** [comment]
It works now, thanks for fixing it so quickly

**Comment by gerwaric** [comment]
Fixed with https://github.com/gerwaric/acquisition/releases/tag/v0.11.1.1
