### ISSUE TITLE
HTTP error 204 in HEAD reply for 'GET /stash/<league>'

### ISSUE THREAD

**Issue by duarm** [gerwaric/acquisition#51]
Latest 0.11.1 release linux appimage, I'm playing on Settlers, and selected "Settlers" during login, the error is triggered when trying to refresh a selected tab, also happens when trying to refresh all tabs, with an additional `204 GET /character/<league>`

```
HTTP error 204 in HEAD reply for 'GET /stash/<league>'
```

Didn't happen on 0.11.0, although I can't confirm if  it was a poe change or not

**Comment by gerwaric** [comment]
It sounds like you might have run across one of the issues I mentioned in the release notes.

I haven't been able the replicate this bug myself, but it should have triggered a bugsplat crash report. I'll take a look when I get home.

**Comment by duarm** [comment]
There was a bugsplat crash report and I pasted the contents, here's the `--log-level TRACE` output if it helps. Let me know if you need anything and thanks.

```
TRACE 2024-07-29T14:58:41.183 ItemsManagerWorker::Update() entered 
DEBUG 2024-07-29T14:58:41.183 Updating Selected stash tabs 
TRACE 2024-07-29T14:58:41.183 ItemsManagerWorker::Update() updating selected tabs 
DEBUG 2024-07-29T14:58:41.183 Updating 1  tabs. 
TRACE 2024-07-29T14:58:41.183 ItemsManagerWorker::RemoveUpdatingTabs() entered 
DEBUG 2024-07-29T14:58:41.183 Keeping 5 tabs and culling 1 
TRACE 2024-07-29T14:58:41.183 ItemsManagerWorker::RemoveUpdatingItems() entered 
DEBUG 2024-07-29T14:58:41.183 Keeping 126 items and culling 26 
TRACE 2024-07-29T14:58:41.183 ItemsManagerWorker::OAuthRefresh() entered 
TRACE 2024-07-29T14:58:41.183 ItemsManagerWorker::MakeOAuthStashListRequest() entered 
TRACE 2024-07-29T14:58:41.183 ItemsManagerWorker::OAuthRefresh() requesting stash list: "https://api.pathofexile.com/stash/Settlers" 
TRACE 2024-07-29T14:58:41.183 RateLimiter::Submit() entered 
TRACE 2024-07-29T14:58:41.183 RateLimiter::Submit() endpoint = "GET /stash/<league>" 
TRACE 2024-07-29T14:58:41.183 RateLimiter::Submit() network_request = "https://api.pathofexile.com/stash/Settlers" 
DEBUG 2024-07-29T14:58:41.183 OAuthManger::Submit() sending a HEAD for a new endpoint: "GET /stash/<league>" 
TRACE 2024-07-29T14:58:41.183 OAuthManager::setAuthorization() entered 
TRACE 2024-07-29T14:58:41.398 RateLimiter::SetupEndpoint() entered 
TRACE 2024-07-29T14:58:41.398 RateLimiter::SetupEndpoint() endpoint = "GET /stash/<league>" 
TRACE 2024-07-29T14:58:41.398 RateLimiter::SetupEndpoint() network_request = "https://api.pathofexile.com/stash/Settlers" 
FATAL 2024-07-29T14:58:41.398 "HTTP error 204 in HEAD reply for 'GET /stash/<league>'" 
```

**Comment by Squirtrex** [comment]
Also having the same issue, let me know if you need any additional info.

**Comment by gerwaric** [comment]
Thanks for the details. I'm out right now but I have some ideas I will need some help testing because this issue doesn't happen to me.  I'll try to get a build out in a couple hours.

This is more fun than league start, which I was never very good at. (10 hours to maps and only about 2div to my name after two full days)

**Comment by duarm** [comment]
I'm quite literally killing myself with my Cast on damage Taken Loop, I'm on the verge of code something too

**Comment by gerwaric** [comment]
I have a test build that might fix this:

https://github.com/gerwaric/acquisition/releases/tag/v0.11.1.1-alpha.1

If this works I'll close this issue and release v0.11.1.1

**Comment by duarm** [comment]
It worked, thanks

**Comment by gerwaric** [comment]
Fixed with https://github.com/gerwaric/acquisition/releases/tag/v0.11.1.1
