### ISSUE TITLE
Mod filtering not working in v11 releases

### ISSUE THREAD

**Issue by wallacrs** [gerwaric/acquisition#57]
Switched to v11.2rc1 and found that after selecting a mod from the dropdown, my tab item list is not automatically filtered (as it used to in older versions). Filtering by socket count, armor, etc (selection above mod list) all work fine.
I was previously using 10.3 but it seems to have stopped being able to connect to servers to download tab list (error just after opening)
Don't get any errors showing in log.txt (default INFO logging).
TRACE logging shows multiple instances of:
```
TRACE 2024-08-03T19:14:14.743 MainWindow::OnLayoutChanged() entered 
TRACE 2024-08-03T19:14:14.743 MainWindow::OnLayoutChange() nothing was selected
```
when making a selection in the mod list dropdown. Tried quite a few different mods, none seemed to trigger any filtering of item list.
Can help with further info if needed to reproduce the issue.
Thanks!

**Comment by gerwaric** [comment]
Thanks for the bug report. I'll take a look at it later this morning and get back to you.

**Comment by gerwaric** [comment]
I was able to reproduce this error, and I think this should fix it:

https://github.com/gerwaric/acquisition/releases/tag/v0.11.2-rc.2

Let me know if this works for you.

**Comment by wallacrs** [comment]
Hi. Thanks for the quick fix - however it seems the Windows .exe on Github
has been built for RC1 rather than RC2 (the file size is also identical to
the original RC1 release). Is it possible to please get a re-build of RC2
for Windows?
[image: image.png]

**Comment by gerwaric** [comment]
Good catch. I replaced the RC1 installer with RC2.

**Comment by wallacrs** [comment]
That's got it, filtering now working again on mods. Thanks for the quick update, and for all the work you've put in to keep Acquisition up and running! I play SSF but Acq is super-handy for me to find all the random gear I find and keep stashed away in case it might be useful on a different character. Cheers!

**Comment by gerwaric** [comment]
Thanks and good luck!
