### ISSUE TITLE
Acquisition still wants to have my SESSION ID even through OAuth login option

### ISSUE THREAD

**Issue by Jhaden0027** [gerwaric/acquisition#64]
I noticed that my shop isn't updating and is giving this error message:

Can't update shop -- cannot extract CSRF token from the page. Check if thread ID is valid. If you're using Steam to login make sure you use the same login method (steam or login/password) in Acquisition, Path of Exile website and Path of Exile game client. For example, if you created a shop thread while using Steam to log into the website and then logged into Acquisition with login/password it will not work. In this case you should either recreate your shop thread or use a correct login method in Acquisition. 

At first, I tried reauthenticating, but to no avail. That's why I used the POESESSID option to login which for some reason worked. Then later, I tried to OAuth again and updating the shop worked again, I noticed the pattern here and tried to change the POESESSID to random characters and I used OAuth again and the same error came back. Then I  tried to leaving the poesseid empty and it's not saying empty POESESSID. I don't know when did this happen but it's really weird and I ASSUME it's a bug. Thanks!

**Comment by gerwaric** [comment]
I think you're right. I believe you cannot currently use OAuth login to update your forum shops.

The settings menu has a place to update your POESSID, but there's no indication that this is needed to update the forum shops. I will look for a place to add this check and notify users so they aren't left confused.

**Comment by gerwaric** [comment]
This update doesn't fix the issue that you still need to use POESESSID to manage forum threads even when you have authenticated with OAuth, but it gives better error messages:

https://github.com/gerwaric/acquisition/releases/tag/v0.11.3
