### ISSUE TITLE
Request to developer: since you have contact with GGG and they listen to You, can you talk with them so they create some new API to be able to look inside the unique collection tab?

### ISSUE THREAD

**Issue by came-here-to-learn** [gerwaric/acquisition#71]
Unique collection tab is not indexed.

The new flask and gem tabs can be indexed.

**Comment by gerwaric** [comment]
A couple of the special tabs are implemented as nested tabs, which includes unique and map tabs. This will be hard to do with the current way acquisition is designed right now. Acquisition's architecture was created 10 years ago, and as the game has grown, things have been bolted on.

However, I'm working on a full rewrite from the ground up that will handle nested tabs. Look for an alpha later this year.

**Comment by gerwaric** [comment]
I'm going to close this issue for now, since it's a feature that's on the roadmap already.
