### ISSUE TITLE
Sorting of character names

### ISSUE THREAD

**Issue by came-here-to-learn** [gerwaric/acquisition#72]
Character names are sorted in a strange way:
First characters with names that start with Capital letters, then names that start with small letters.

Could this please be changed?

E.g. it looks like this

Anna
AnnaTheThird
Bob
Clara
Diana
Edmund
annaTheSecond
bobTwo
claraTwo
dianaTwo
edmundTwo

**Comment by gerwaric** [comment]
This should be doable. I might have to time to work on it next week.

**Comment by gerwaric** [comment]
This issue should be addressed by https://github.com/gerwaric/acquisition/releases/tag/v0.11.6

Please let me know if it works for you.
