### ISSUE TITLE
Error updating shop thread: missing 'realm' attribute

### ISSUE THREAD

**Issue by forry** [gerwaric/acquisition#75]
Hi,
today the acquisition started to show: `Error submitting shop thread: "linkItem tag missing 'realm' attribute"`. I have found a thread about that [https://www.pathofexile.com/forum/view-thread/3587124](https://www.pathofexile.com/forum/view-thread/3587124). Seems they fixed it for the forum but acquisition still showing that error even after the acq. restart and history clear in the browser.

**Comment by gerwaric** [comment]
Thank you for reporting this error.

I saw in the thread you linked that GGG may have addressed this issue already.

However, I'll make time to check this later today. If we need to add the realm attribute, I'll figure out how to do that--either manually or automatically if possible.

**Comment by gerwaric** [comment]
This should be fixed with https://github.com/gerwaric/acquisition/releases/tag/v0.11.7

**Comment by forry** [comment]
I'm just testing it, and it is indeed fixed. Thank you very much for your swift reaction.
