### ISSUE TITLE
Application closes immediately after login

### ISSUE THREAD

**Issue by dotas86** [gerwaric/acquisition#81]
What the title says, it immediately closes. I have authenticated and when I press login, it closes and nothing happens.
0.11.8 release

**Comment by gerwaric** [comment]
Thank you for the heads up. I'm seeing some crashes on [bugsplat](https://bugsplat.com/) that look like a Microsoft Visual C++ runtime error. Did you install the Visual C++ runtime when you installed acquisition?  If not, reinstalling with this option enabled is the first thing I'd try.

**Comment by dotas86** [comment]
I had already installed it before so I did not choose to reinstall. I just did and it fixed  it! Thanks a bunch!

**Comment by gerwaric** [comment]
Awesome.

Now I just need to find a way to determine if the right version of VC++ is being at runtime, because failing silently without an error message is.. not the best user experience.
